# Generated by Django 5.1.3 on 2024-12-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_country_alter_userprofile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
