# Generated by Django 5.1.3 on 2024-12-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('IN', 'India'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('DE', 'Germany'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('NO', 'Norway'), ('SE', 'Sweden'), ('DK', 'Denmark'), ('FI', 'Finland'), ('PL', 'Poland'), ('PT', 'Portugal'), ('IE', 'Ireland'), ('LU', 'Luxembourg'), ('AT', 'Austria'), ('CH', 'Switzerland'), ('CZ', 'Czech Republic'), ('HU', 'Hungary'), ('SK', 'Slovakia'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('GR', 'Greece'), ('CY', 'Cyprus'), ('MT', 'Malta'), ('LI', 'Liechtenstein'), ('VA', 'Vatican City'), ('MC', 'Monaco'), ('SM', 'San Marino'), ('VA', 'Vatican City')], max_length=2),
        ),
    ]
